---
# Example using filters, ignoring permission errors, and specifying the hostname precedence
plugin: aws_ec2

aws_access_key: env: AWS_ACCESS_KEY_ID
aws_secret_key: env: AWS_SECRET_KEY_ID
# Populate inventory with instances in these regions
regions:
  - eu-west-1
filters:
  # All instances with their `Environment` tag set to `dev`
  tag:Environment: Saskia.Testing.Env

# Ignores 403 errors rather than failing
strict_permissions: False
